import './globals.css'
import * as dotenv from 'dotenv'
import Sidebar from './components/molecules/Sidebar'
import Container from '@mui/material'

dotenv.config()

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            {/* <nav>
                <a href="/">Home</a>
                <a href="/pages/posts">Posts</a>
            </nav> */}
                <main style={{display: "flex", width: "100%"}}>
                    <Sidebar/>
                    <div style={{width: "100%"}}>{children}</div>
                </main>
        </body>
    </html>
  )
}
